### ISSUE TITLE
Template non compability with Zabbix 3.0

### ISSUE THREAD

**Issue by JamesDeGreese** [Lelik13a/Zabbix-Supervisor-Check#1]
Please notate in readme file that this template noncompabile with Zabbix 3.0. XML file can't be imported in older versions, because file syntax contains version tag and some unexpected tags, i.e <manual_close> or <recovery_expression/>.
If it possible, create some xml templates for other zabbix versions, or notate on this page https://share.zabbix.com/cat-app/app-other/supervisor-check about zabbix 3.2 only support.

**Comment by Lelik13a** [comment]
I changed description on share.zabbix.com. 
I can't export template for older version, because everywhere use 3.2.x. But you can simple delete unexpected tags and fields from template and import it.
I'll be glad to add a tested template for older versions.

**Comment by JamesDeGreese** [comment]
Yep))) I already changed xml file manually by editing version value and delete unexpected tags. All working fine.
In additional i want to say that perl script require libswitch-perl library, please add this to instalation guide as requirements.
